### ISSUE TITLE
Move gh-pages branch to a docs folder in master 

### ISSUE THREAD

**Issue by SBats** [makinacorpus/makina-slides#2]
Hey, I was thinking, thx to the new gh-pages system of github, we can now [use a `docs` folder on master branch to serve gh-pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch).

Wouldn't it be easier to keep everything in the master branch and get rid of the heavy process of having to clone twice the repo to generate and publish slides ?

Waiting for people opinion on this one :)

**Comment by ghost** [comment]
+1

**Comment by SebCorbin** [comment]
Done !
